= idris2-devcontainer
:experimental:
:source-highlighter: rouge
:source-language: shell
:icons: font
:sectanchors:
:star: *
Markus Dangl <663399+xicesky@users.noreply.github.com>

Containers for https://idris-lang.org/[idris2] development

* Built from the https://github.com/xicesky/idris2-devcontainer[Dockerfiles here]
* Images hosted on https://github.com/xicesky?tab=packages&repo_name=idris2-devcontainer[github packages]

== How to use

* You can run idris2 or pack from the "idris2" docker container:
+
[source,bash]
----
docker run --rm -it ghcr.io/xicesky/idris2:nightly-230701-ubuntu-22.04 idris2
# or
docker run --rm -it ghcr.io/xicesky/idris2:nightly-230701-ubuntu-22.04 pack repl
----
* The devcontainer image can be used for your idris2 project, see for example my https://github.com/xicesky/idris2-stuff[idris2-stuff] repository.
    The `.devcontainer` directory contains the Dockerfile that uses this devcontainer and customizes it.

== Published containers

* `ghcr.io/xicesky/idris2-base:ubuntu-22.04`
    ** Base container for building idris2
* `ghcr.io/xicesky/idris2:nightly-230701-ubuntu-22.04`
    ** Container with installed idris2 & https://github.com/stefan-hoeck/idris2-pack[pack]
* `ghcr.io/xicesky/idris2-devcontainer:nightly-230701-ubuntu-22.04`
    ** https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-development-container[Visual Studio Code Development Container] for idris2 development
    ** Includes https://github.com/idris-community/idris2-lsp[idris2-lsp]

== Development

Requirements:

* https://pre-commit.com/[pre-commit] (optional), install e.g. using `pip install pre-commit`
* docker
* bash

[source,console]
----
$ git clone git@github.com:xicesky/idris2-devcontainer.git
$ cd idris2-devcontainer
$ pre-commit install

Build the containers:
$ ./build-locally.sh
----

In order to push the containers, Visit https://github.com/settings/tokens[create a personal access token on github] and use that token in the following commands to log in to the github container registry:

[source,console]
----
Read github personal access token, the login using docker.
$ read -rs CR_PAT
$ echo $CR_PAT | docker login ghcr.io -u xicesky --password-stdin

Push the containers with:
$ ./push-local-builds.sh
----

=== Maintenance

[source,console]
----
Also, update pre-commit hooks from time to time:
$ pre-commit autoupdate
$ pre-commit run --all-files
$ git add -A && git commit -m "Update pre-commit hooks"
----
